name: Build Maven project and deploy to lmabda
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build the package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
              ${{ runner.os }}-maven-
      - name: Setup jdk 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          java-package: jdk
      - name: Build and test project
        run: mvn clean compile package --file pom.xml

  upload-to-aws-lambda:
    needs: build
    name: Upload to aws lambda
    runs-on: ubuntu-20.04
    steps:
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          function_name:
          zip_file: AwsLearning-1.0-SNAPSHOT.jar





