name: Build Maven project and deploy to ,\
on: [push]
jobs:
  build-deploy-to-aws:
    runs-on: ubuntu-20.04
    name: Build the package and deploy to aws ,\
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
              ${{ runner.os }}-maven-
      - name: Setup jdk 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          java-package: jdk
      - name: Build and test project
        run: |
          mvn clean compile package --file pom.xml -Dmaven.test.skip
          mkdir staging && cp target/*.jar staging

      - name: default java-create-user-fun deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          function_name: java-create-user-fun
          zip_file: staging/AwsLearning-1.0-SNAPSHOT.jar
          aws_region: ap-south-1

      - name: default java-list-users-fun deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          function_name: java-list-users-fun
          zip_file: AwsLearning-1.0-SNAPSHOT.jar
          aws_region: ap-south-1




